select count(*) from user;

select distinct idproduct, group_concat(iduser) 
from review 
where iduser > 1 and iduser < 50000
group by iduser;

select * from category where parent is null;

select * from review limit 100;

select count( distinct iduser)

select idproduct, group_concat(iduser)

select group_concat(iduser separator ' ')
from review 
where idproduct in (select idproduct from product where idcategory in (select idcategory
				from category
				where name in (
'Enterprise Storage'
,'Other Power Accessories'
,'Network Storage'
,'Office Chairs'
,'Multimedia Projectors'
,'Bath & Hygiene Accessories'
,'High Chairs'
,'Tablet PCs'
,'Serial Adapters'
,'Photograph Storage & Display'
,'Safety & Emergency Electronics'
,'Office Accessories'
,'Hiking Poles'
,'Cradles'
,'--Books'
,'Feeding Accessories'
,'Storage Controllers'
,'Car Video Players'
,'Graphic Tablets'
,'Floppy Drives'
,'Scooters'
,'Safety & Emergency Security Products'
,'Travel Accessories & Handbags'
,'Glucose & Cholesterol Monitors'
,'Tape Drives'
,'Hubs and Switches'
,'Guitars & Basses'
,'Locks & Guards'
,'Crib Mattresses'
,'Baby Monitors'
,'Beds'
,'Amplifiers'
,'N-Gage Games'
,'Scanner Accessories'
,'Mobile Audio/Video'
,'Transceivers'
,'Bikes'
,'Small Appliances'
,'Routers and Bridges'
,'Read Only Memory (ROM)'
,'Keyboards & MIDI'
,'Enterprise Computing Accessories'
,'Toys'
,'Pianos'
,'Beds'
,'Shop Tool Accessories'
,'Computer Games'
,'PDAs'
,'Books'
,'Office Supplies'
,'Toys'
,'PlayStation 1 Games'
,'Wines'
,'Specialty Kitchen Appliances'
,'Cookware'
,'Used Cars'
,'Cars'
,'Baby Care'
,'Cartridges and Toners'
,'Cosmetics'
,'Tableware'
,'Mac Laptops'
,'Watches'
,'Fragrance'
,'Clothing'
,'Keyboards and Mice'
,'Mac Desktops'
,'Printers'
,'Musical Instruments'
,'Spirits and Beers'
,'Software'
,'Shoes'
,'Flash Memory'
,'Nintendo 64 Games'
,'Laptop Accessories'
,'Outdoor Apparel'
,'Monitors'
,'Computer Speakers'
,'Luggage'
,'Gifts, Novelties, Collectibles & Gadgets'
,'PlayStation 2 Games'
,'Cooking Tools'
,'Dishwashers'
,'Washing Machines'
,'Tools and Accessories'
,'Mixers'
,'Vacuum Cleaner Accessories'
,'Shredders'
,'Crock Pots and Slow Cookers'
,'Air Purifiers'
,'Coffee and Espresso Makers'
,'Refrigerators'
,'Kitchen Ranges'
,'Microwave Ovens'
,'Indoor Grills and Sandwich Makers'
,'Car Seats'
,'Electric Fans'
,'Cutlery'
,'Blenders'
,'Tires'
,'Scanners'
,'PC Desktops'
,'Deep Fryers'
,'Mattresses'
,'Sewing Machines'
,'Furniture'
,'Freezers'
,'Shavers'
,'Grill and Smoker Accessories'
,'Toasters'
,'Drapes & Curtains'
,'Small Appliance Accessories'
,'Juicers'
,'Pasta Makers'
,'PC Gaming Devices'
,'Graphics Cards'
,'Humidifiers'
,'Marine Electronics'
,'Video Game Consoles'
,'Glue & Adhesives'
,'Fax Machines'
,'Headsets'
,'PC Laptops'
,'Random Access Memory (RAM)'
,'Processors'
,'Motherboards'
,'CD and DVD Burners'
,'Input Adapters'
,'Computer Accessories'
,'Hard Drives'
,'Web Cameras'
,'Networking Hubs and Switches'
,'Radar Detectors'
,'Sound Cards'
,'Tablets'
,'Motorcycles'
,'Security Systems'
,'Removable Media'
,'Coffee and Tea Makers'
,'Computer Supplies'
,'Coffee Grinders'
,'PDA Accessories'
,'Popcorn Makers'
,'Classic Consoles'
,'Appliance Accessories'
,'Memory Adapters'
,'Modems'
,'Network Accessories'
,'Cables and Connectors'
,'UPS Systems Devices'
,'Toaster Ovens'
,'Car Racks'
,'Clothing Accessories'
,'Beers'
,'Routers'
,'Surge Suppressors'
,'GPS Accessories'
,'DS Games'
,'Wireless Adapters'
,'Liquor & Spirits'
,'PlayStation 3 Games'
,'GameCube Games'
,'Bread Machines'
,'Toddler Beds'
,'Dreamcast Games'
,'Xbox 360 Games'
,'Nintendo Wii Games'
,'Game Boy Advance Games'
,'Video Game Accessories'
,'PSP Games'
,'Xbox Games'
,'Strollers'
,'Video Games'
,'CD-ROM Drives'
,'Baby Carriers'
,'Sunglasses'
,'Itch Relief'
,'Earplugs'
,'Rice Cookers and Steamers'
,'Shampoo'
,'Conditioner'
,'Copiers'
,'Styling Aids'
,'Cribs and Bassinets'
,'Air Conditioners'
,'Dehumidifiers'
,'Electric Kettles'
,'Motorsports Accessories'
,'Exercise Equipment'
,'Pest Control'
,'Network Cables'
,'Shop Tools'
,'USB and Firewire Hubs'
,'Network Adapters'
,'Garden Tools'
,'KVM Switches'
,'Styling Tools'
,'Walking Shoes'
,'Eye Makeup'
,'Face Makeup'
,'Sports Bras'
,'Ankle Braces'
,'Golf Clubs'
,'Patio Furniture'
,'Fishing Gear & Accessories'
,'Boats'
,'Boat Motors'
,'Typewriters'
,'Ovens'
,'Kitchen Cooktops'
,'Baby Foods'
,'Play Pens'
,'Baby Activity'
,'Bottles'
,'Ice Cream Makers'
,'Diaper Accessories'                
)))
group by idproduct;